### ISSUE TITLE
All compounds are 'not clean'

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#2]
It seems to want to clean all compounds, regardless of whether they need it or not. This can be misleading. 

I pasted a simple benzene ring from the templates (perfectly drawn) and when I went to save to chembl, it said it wasn't clean, when it obviously is.

**Comment by mnowotka** [comment]
In the context of curation interface, the definition of 'clean' molfile is as follows:

The molfile is considered clean if it contains 

```
> <UPDATED>
```

property. This means that every molfile created by marvin will not be considered as clean.
This is by design. What we want to achieve here is to be sure that 'clean' file have been passed through our standard and official PP protocol and nothing else.

Anyway, if you want to skip questions about cleaning molfiles, go to `Settings` -> `show all settings` -> `Clean up compounds` and choose `Never`.

Then, if you click `Apply`, curation interface will not ask you to clean a molfile until you refresh the website. If you click `Save as profile`, curation interface will not ask you to clean as long as your cookie is valid (few weeks).

**Comment by ljbellis** [comment]
Yes, I know that you can set this, but in terms of 'chemistry' you're definition of 'clean' is incorrect. Rather than asking them if they want to 'clean' it, as techincally you're not clenaing it, just add this property and don't give people the option. It's a misleading statement, in my opinion.

**Comment by mark-davies** [comment]
Would it make sense to remove the "Molfile in seems not to be clean." statement from the pop-up?

**Comment by ljbellis** [comment]
I would. It's misleading. If this property is something that you want, or if you want to run our own clean up in the background, I would do it anyway and not give the user an option.

**Comment by mark-davies** [comment]
Remove the text

**Comment by mnowotka** [comment]
Done.
