### ISSUE TITLE
Pop up windows when clicking on Doc ID

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#26]
After creating a new record in http://sark.ebi.ac.uk:3021/curation/curate#1763547 I clicked on the doc_id for new record in the row and two 'Choose A Document' empty pop up boxes appeared.

**Comment by mnowotka** [comment]
When you say 'empty' does it mean that there is nothing inside or there are some textareas and they are empty? Showing the popup after clicking on doc_id is expected behavior. Here I assume that the curator doesn't know doc_id but wants to find/create one. So the popup here is to help doing this. It it's totally empty this is clearly a bug, can you check if you see the same using firefox?

**Comment by ljbellis** [comment]
No the doc id is there and they've just clicked on it, maybe to confirm that's the one they want to curate. 

The fields are empty. 

To make it easier - go to molregno 250

Click on any doc id for any of the compound records. 
A pop up for Add a document appears with the fields unpopulated. 

This doesn't make sense. 

One would expect them to be populated with the data from that doc id.

They can always change it but it would make more sense if when they click on the doc id they get to see the journal info. 

Should they then wish to change this, then they can but they may just want to see the info.

**Comment by mnowotka** [comment]
Related to https://github.com/chembl/curation-interface/issues/57
