### ISSUE TITLE
Move things around in 'Choose Document' window

### ISSUE THREAD

**Issue by ljbellis** [chembl/curation-interface#57]
When adding a new record and you've clicked on 'Find Document'

I think Find Document should be changed to 'Create Document' as that is what you're doing

In the window, I would move

Type - to the very top

Have the lower fields dependent on what you choose. 

So, if it's Book, you should have ISBN number

If it's Dataset you could have experiment names of scientists, total number of compounds in set for example - you wouldn't necessarily have a publication

Then if it's piblication, you would then have Title, author etc etc

**Comment by mnowotka** [comment]
OK, so I think here we are at the source of misconception related to 'Choose a Document' dialog. Let me explain:

The dialog with `Choose a document` title appears in many places in the curation interface. It will show up when you click on `Documents` item in the top menu. The same dialog will pop up when you click `Find a document` button in `Add new record dialog` (https://github.com/chembl/curation-interface/issues/56). It will also appear then you click on any document id in the 'Records table' (https://github.com/chembl/curation-interface/issues/68).

What this dialog was designed for?
1. Creating a new row in Docs table. Docs table doesn't have 'ISBN' column so I can't add ISBN field even if the type is Book.
2. Finding existing documents. There is no need to create a new row in Docs if it already exists. You can check if the row exists by specifying doc_id/DOI/PubMed. Alternatively you can provide pdf file in which case curation interface will extract a DOI from the pdf and look it up in ChEMBL and Entrez. If a document is found in Docs table the dialog closes immediately and doc_id field is populated with found document. 

What this dialog wasn't designed for?
1. Creating new row in Journals table - this is currently out of scope of curation interface but can be changed if necessary.
2. Presenting information about already chosen document - again can be (and probably will be) changed.

So this is why I insist on having the first button named 'Create' - because it indicates that clicking on it will create a new row in Docs Table so this is important operation and requires interaction with DB. If this button is named 'OK' it says nothing.

Anyway, I will link all tickets related to 'Choose a document' dialog to this one and close the rest as duplicates. Also, I'm assigning Mark here as this issue requires some design decisions to be made.

![screen shot 2014-11-25 at 10 24 38](https://cloud.githubusercontent.com/assets/837119/5181339/4b8c74e4-748d-11e4-893e-c5442dddc334.png)

**Comment by mnowotka** [comment]
But I will move type field to the very top as requested.

**Comment by ljbellis** [comment]
'Choose a document' and 'Create' have two completely different meanings.
Choose implies that it already exists.
Create implies something new.
That's why I suggested changing 'Create' to 'OK'. This gets rid of most of the issue.

**Comment by mnowotka** [comment]
Let me explain:

If using this window you manage to find document that already exists in ChEMBL, it will be closed immediately.

If this is a new document, you have to click on the button to confirm creating a new object in DB. This is the exact reason why the button has 'Create' as it's name. 

Anyway, this issue is central to all issues related to creation/retrieval of document and all other isues should be closed.

**Comment by mnowotka** [comment]
Forgot to say, type has been moved to the very top.

**Comment by mnowotka** [comment]
The 'Documents' dialog has been improved. So we should probably review this issue it there are any thing that still require improvements.

**Comment by ljbellis** [comment]
yes
